In [1]:
import numpy as np
import pandas as pd

In [2]:
def _read_observation_file(filename):
    df = pd.read_csv(filename, sep=r"\s+")
    return df


def write_data(df, filename_out):
    """writes the data extracted from input and result files to
    filename_out

    Parameters
    ----------
    df : pd.DataFrame
        data to be written
    filename_out : string
        name of the output file in which the data should be written
    """
    header = "   ".join(df.columns) + "\n"

    with open(filename_out, "w") as f:
        f.write(header)

    # convert the list of dicts to a dataframe
    for col in df.columns[1:]:
        df[col] = df[col].apply(lambda x: f"{float(x):.4E}")

    # fuse the columns of the dataframe
    df_1col = df.apply(lambda row: "   ".join(list(row)) + "\n", 1)

    # save to output file
    with open(filename_out, "a") as f:
        for i in range(len(df_1col)):
            f.write(df_1col.at[i])

In [10]:
mode = "Int"
df = _read_observation_file(f"./OrionBar_Joblin_{mode}_full.dat")
df.head()

,X_Y,CO_(4-3),CO_(5-4),CO_(6-5),CO_(7-6),CO_(8-7),CO_(9-8),CO_(10-9),CO_(11-10),CO_(12-11),...,O_145_mic,O_63_mic,H2_0-0_S(0),H2_0-0_S(1),H2_0-0_S(2),H2_0-0_S(3),H2_0-0_S(4),H2_0-0_S(5),H2_1-0_S(1),H2_2-1_S(1)
0,00_00,3.000000e-07,7.600000e-07,0.000001,0.000002,0.000002,0.000003,0.000003,0.000003,0.000003,...,0.000021,0.00019,9.000000e-07,0.000004,0.000002,0.000006,0.000002,0.000006,4.700000e-07,1.200000e-07

In [11]:
df["X"] = df["X_Y"].apply(lambda x: x.split("_")[0])
df["Y"] = df["X_Y"].apply(lambda x: x.split("_")[1])
df = df.drop(["X_Y"], 1)
df = df.astype(float)
df[["X", "Y"]] = df[["X", "Y"]].astype(int)
df = df.set_index(["X", "Y"])
df.head()

/tmp/ipykernel_641671/687504521.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df = df.drop(["X_Y"], 1)

,,CO_(4-3),CO_(5-4),CO_(6-5),CO_(7-6),CO_(8-7),CO_(9-8),CO_(10-9),CO_(11-10),CO_(12-11),CO_(13-12),...,O_145_mic,O_63_mic,H2_0-0_S(0),H2_0-0_S(1),H2_0-0_S(2),H2_0-0_S(3),H2_0-0_S(4),H2_0-0_S(5),H2_1-0_S(1),H2_2-1_S(1)
X,Y,,,,,,,,,,,,,,,,,,,,,
0,0,3.000000e-07,7.600000e-07,0.000001,0.000002,0.000002,0.000003,0.000003,0.000003,0.000003,0.000002,...,0.000021,0.00019,9.000000e-07,0.000004,0.000002,0.000006,0.000002,0.000006,4.700000e-07,1.200000e-07

In [12]:
# conversion from W m$^{-2}$ sr$^{-1}$   to  erg cm$^{-2}$ s$^{-1}$ sr$^{-1}$
df *= 1e3

In [13]:
df.columns

Index(['CO_(4-3)', 'CO_(5-4)', 'CO_(6-5)', 'CO_(7-6)', 'CO_(8-7)', 'CO_(9-8)',
       'CO_(10-9)', 'CO_(11-10)', 'CO_(12-11)', 'CO_(13-12)', 'CO_(14-13)',
       'CO_(15-14)', 'CO_(16-15)', 'CO_(17-16)', 'CO_(18-17)', 'CO_(19-18)',
       'CO_(20-19)', 'CO_(21-20)', 'CO_(23-22)', '13CO_(5-4)', '13CO_(6-5)',
       '13CO_(7-6)', '13CO_(8-7)', '13CO_(9-8)', '13CO_(10-9)', '13CO_(11-10)',
       '13CO_(12-11)', '13CO_(13-12)', '13CO_(15-14)', '13CO_(16-15)',
       'CH+_(1-0)', 'CH+_(2-1)', 'CH+_(3-2)', 'CH+_(4-3)', 'CH+_(5-4)',
       'CH+_(6-5)', 'OH_(02-00)_119.4416_mic', 'OH_(3-1)_119.2345_mic',
       'OH_(4-0)_79.1792_mic', 'OH_(5-1)_79.171156_mic',
       'OH_(6-4)_163.3962_mic', 'OH_(7-5)_163.0153_mic',
       'OH_(8-2)_84.5967_mic', 'OH_(9-3)_84.4203_mic', 'OH_(12-8)_65.2789_mic',
       'OH_(13-9)_65.1318_mic', 'HD_(1-0)_112.07_mic', 'HD_(2-1)_56.23_mic',
       'C+_158_micr', 'C_609_mic', 'C_370_mic', 'O_145_mic', 'O_63_mic',
       'H2_0-0_S(0)', 'H2_0-0_S(1)', 'H2_0-0_S(2)', 'H2_0-0_S(3)',
       'H2_0-0_S(4)', 'H2_0-0_S(5)', 'H2_1-0_S(1)', 'H2_2-1_S(1)'],
      dtype='object')

In [14]:
df = df.rename(
    columns={
        "CO_(4-3)": "co_v0_j4__v0_j3",
        "CO_(5-4)": "co_v0_j5__v0_j4",
        "CO_(6-5)": "co_v0_j6__v0_j5",
        "CO_(7-6)": "co_v0_j7__v0_j6",
        "CO_(8-7)": "co_v0_j8__v0_j7",
        "CO_(9-8)": "co_v0_j9__v0_j8",
        "CO_(10-9)": "co_v0_j10__v0_j9",
        "CO_(11-10)": "co_v0_j11__v0_j10",
        "CO_(12-11)": "co_v0_j12__v0_j11",
        "CO_(13-12)": "co_v0_j13__v0_j12",
        "CO_(14-13)": "co_v0_j14__v0_j13",
        "CO_(15-14)": "co_v0_j15__v0_j14",
        "CO_(16-15)": "co_v0_j16__v0_j15",
        "CO_(17-16)": "co_v0_j17__v0_j16",
        "CO_(18-17)": "co_v0_j18__v0_j17",
        "CO_(19-18)": "co_v0_j19__v0_j18",
        "CO_(20-19)": "co_v0_j20__v0_j19",
        "CO_(21-20)": "co_v0_j21__v0_j20",
        "CO_(23-22)": "co_v0_j23__v0_j22",
        #
        "13CO_(5-4)": "13c_o_j5__j4",
        "13CO_(6-5)": "13c_o_j6__j5",
        "13CO_(7-6)": "13c_o_j7__j6",
        "13CO_(8-7)": "13c_o_j8__j7",
        "13CO_(9-8)": "13c_o_j9__j8",
        "13CO_(10-9)": "13c_o_j10__j9",
        "13CO_(11-10)": "13c_o_j11__j10",
        "13CO_(12-11)": "13c_o_j12__j11",
        "13CO_(13-12)": "13c_o_j13__j12",
        "13CO_(15-14)": "13c_o_j15__j14",
        "13CO_(16-15)": "13c_o_j16__j15",
        #
        "CH+_(1-0)": "chp_j1__j0",
        "CH+_(2-1)": "chp_j2__j1",
        "CH+_(3-2)": "chp_j3__j2",
        "CH+_(4-3)": "chp_j4__j3",
        "CH+_(5-4)": "chp_j5__j4",
        "CH+_(6-5)": "chp_j6__j5",
        #
        "OH_(02-00)_119.4416_mic": "oh_j5_2_pp_fif2__j3_2_pm_fif2",
        "OH_(3-1)_119.2345_mic": "oh_j5_2_pm_fif2__j3_2_pp_fif2",
        "OH_(4-0)_79.1792_mic": "oh_j1_2_pp_fif1__j3_2_pm_fif2",
        "OH_(5-1)_79.171156_mic": "oh_j1_2_pm_fif1__j3_2_pp_fif2",
        "OH_(6-4)_163.3962_mic": "oh_j3_2_pm_fif1__j1_2_pp_fif1",
        "OH_(7-5)_163.0153_mic": "oh_j3_2_pp_fif1__j1_2_pm_fif1",
        "OH_(8-2)_84.5967_mic": "oh_j7_2_pm_fif2__j5_2_pp_fif2",
        "OH_(9-3)_84.4203_mic": "oh_j7_2_pp_fif2__j5_2_pm_fif2",
        "OH_(12-8)_65.2789_mic": "oh_j9_2_pp_fif2__j7_2_pm_fif2",
        "OH_(13-9)_65.1318_mic": "oh_j9_2_pm_fif2__j7_2_pp_fif2",
        #
        "HD_(1-0)_112.07_mic": "hd_v0_j1__v0_j0",
        "HD_(2-1)_56.23_mic": "hd_v0_j2__v0_j1",
        #
        "C+_158_micr": "cp_el2p_j3_2__el2p_j1_2",
        "C_609_mic": "c_el3p_j1__el3p_j0",
        "C_370_mic": "c_el3p_j2__el3p_j1",
        "O_145_mic": "o_el3p_j0__el3p_j1",
        "O_63_mic": "o_el3p_j1__el3p_j2",
        #
        "H2_0-0_S(0)": "h2_v0_j2__v0_j0",
        "H2_0-0_S(1)": "h2_v0_j3__v0_j1",
        "H2_0-0_S(2)": "h2_v0_j4__v0_j2",
        "H2_0-0_S(3)": "h2_v0_j5__v0_j3",
        "H2_0-0_S(4)": "h2_v0_j6__v0_j4",
        "H2_0-0_S(5)": "h2_v0_j7__v0_j5",
        #
        "H2_1-0_S(1)": "h2_v1_j3__v0_j1",
        "H2_2-1_S(1)": "h2_v2_j3__v1_j1",
    }
)

In [15]:
df.head()

,,co_v0_j4__v0_j3,co_v0_j5__v0_j4,co_v0_j6__v0_j5,co_v0_j7__v0_j6,co_v0_j8__v0_j7,co_v0_j9__v0_j8,co_v0_j10__v0_j9,co_v0_j11__v0_j10,co_v0_j12__v0_j11,co_v0_j13__v0_j12,...,o_el3p_j0__el3p_j1,o_el3p_j1__el3p_j2,h2_v0_j2__v0_j0,h2_v0_j3__v0_j1,h2_v0_j4__v0_j2,h2_v0_j5__v0_j3,h2_v0_j6__v0_j4,h2_v0_j7__v0_j5,h2_v1_j3__v0_j1,h2_v2_j3__v1_j1
X,Y,,,,,,,,,,,,,,,,,,,,,
0,0,0.0003,0.00076,0.0012,0.0016,0.002,0.0027,0.0025,0.0028,0.0025,0.0024,...,0.021,0.19,0.0009,0.0037,0.0022,0.006,0.0016,0.0064,0.00047,0.00012

In [16]:
df.to_pickle(f"./OrionBar_Joblin_{mode}.pkl")

In [37]:
# write_data(df, "./OrionBar_Joblin_Int_fit.dat")